In [19]:
import pandas as pd
import json
import glob
from helper import get_metrics_from_cve as get_metrics
import sqlite3
import datetime

## Raw Data

In [2]:
#json to df

rows = []

# Loop over all json files in your raw folder
for filepath in glob.glob("../data/raw/CVE/202[2-5]/**/*.json", recursive=True):
    with open(filepath, "r", encoding="utf-8") as f:
        try:
            data = json.load(f)
            
            # Extract top-level metadata
            meta = data.get("cveMetadata", {})
            cve_id = meta.get("cveId")
            date_pub = meta.get("datePublished")
            state = meta.get("state")
            container = data.get("containers")
            # Extract cna container details
            score,severity,atk_vec ,_ = get_metrics(data.get("containers"))
           
            
            # Extract description
            desc_list = container.get("cna").get("descriptions",[])
            desc = None
            if len(desc_list):
                desc = desc_list[0].get("value")
            

            if cve_id:
                rows.append({
                    "cve_id": cve_id,
                    "date_published": date_pub,
                    "cve_state": state,
                    "score": score,
                    "severity":severity,
                    "attack_vector":atk_vec,
                    "description": desc
                })
            else:
                print(cve_id)
        except Exception as e:
            print(e,filepath)
            continue

# Save as a clean CSV table
df_cve = pd.DataFrame(rows)


In [22]:
# convert data to sql
print(df_cve.head(10))
print(df_cve.shape)
print( datetime.datetime.now())


          cve_id            date_published  cve_state  score severity  \
0  CVE-2022-0001  2022-03-11T00:00:00.000Z  PUBLISHED    6.5   MEDIUM   
1  CVE-2022-0002  2022-03-11T17:54:36.000Z  PUBLISHED    6.5   MEDIUM   
2  CVE-2022-0003                       NaN   REJECTED    NaN      NaN   
3  CVE-2022-0004  2022-05-12T16:36:02.000Z  PUBLISHED    6.8   MEDIUM   
4  CVE-2022-0005  2022-05-12T16:36:04.000Z  PUBLISHED    2.4      LOW   
5  CVE-2022-0010  2023-05-22T07:22:51.662Z  PUBLISHED    7.8     HIGH   
6  CVE-2022-0011  2022-02-10T18:10:15.524Z  PUBLISHED    6.5   MEDIUM   
7  CVE-2022-0012  2022-01-12T17:30:15.528Z  PUBLISHED    6.1   MEDIUM   
8  CVE-2022-0013  2022-01-12T17:30:17.158Z  PUBLISHED    5.0   MEDIUM   
9  CVE-2022-0014  2022-01-12T17:30:18.718Z  PUBLISHED    6.7   MEDIUM   

  attack_vector                                        description  
0         LOCAL  Non-transparent sharing of branch predictor se...  
1         LOCAL  Non-transparent sharing of branch predict

In [24]:
# csv to df
df_nvd = pd.read_csv("../data/raw/known_exploited_vulnerabilities.csv")
print(df_nvd.head())
print(df_nvd.shape)
print(datetime.datetime.now())



            cveID vendorProject                   product  \
0  CVE-2025-39964         Linux                    Kernel   
1  CVE-2026-53266         Linux                    Kernel   
2  CVE-2025-39682         Linux                    Kernel   
3  CVE-2026-58704        Google                     Pixel   
4  CVE-2026-76460         Cisco  Identity Services Engine   

                                   vulnerabilityName   dateAdded  \
0          Linux Kernel Race Condition Vulnerability  2026-09-18   
1     Linux Kernel Out-of-Bounds Write Vulnerability  2026-09-18   
2  Linux Kernel Improper Check for Unusual or Exc...  2026-09-18   
3  Google Pixel Improper Authorization Vulnerability  2026-09-16   
4  Cisco Identity Services Engine Incorrect Use o...  2026-09-16   

                                    shortDescription  \
0  Linux Kernel contains a race condition vulnera...   
1  Linux Kernel contains an out-of-bounds write v...   
2  Linux Kernel contains an improper check for un...   


## SQL Join

In [5]:
#df to sql
conn = sqlite3.connect(':memory:')
df_cve.to_sql('nvd_cves', conn, index=False, if_exists='replace')     
df_nvd.to_sql('cisa_kev', conn, index=False, if_exists='replace')

cursor = conn.cursor()
cursor.execute("DROP TABLE IF EXISTS cisa_nvd_joined;")
cursor.execute("""
    CREATE TABLE cisa_nvd_joined AS
    SELECT 
        -- Common Key (from CISA)
        c.cveID AS cve_id,
        
        -- CISA KEV Columns (from table 'cisa_kev', alias 'c')
        c.vendorProject,
        c.product,
        c.vulnerabilityName,
        c.dateAdded AS cisa_date_added,
        c.shortDescription AS cisa_description,
        c.requiredAction,
        c.dueDate,
        c.knownRansomwareCampaignUse,
        c.forensicTriage,
        c.notes,
        c.cwes,
        
        -- NVD Columns (from table 'nvd_cves', alias 'n')
        n.date_published AS nvd_date_published,
        n.cve_state,
        n.score AS cvss_score,
        n.severity AS cvss_severity,
        n.attack_vector,
        n.description AS nvd_description

    FROM cisa_kev c
    INNER JOIN nvd_cves n 
        ON UPPER(TRIM(c.cveID)) = UPPER(TRIM(n.cve_id));
""")

joined_df = pd.read_sql_query("SELECT * FROM cisa_nvd_joined", conn)





In [25]:
joined_df.shape

(649, 18)

In [26]:
joined_df.sample(10,random_state=42)

,cve_id,vendorProject,product,vulnerabilityName,cisa_date_added,cisa_description,requiredAction,dueDate,knownRansomwareCampaignUse,forensicTriage,notes,cwes,nvd_date_published,cve_state,cvss_score,cvss_severity,attack_vector,nvd_description
636,CVE-2022-20708,Cisco,"Small Business RV160, RV260, RV340, and RV345 ...",Cisco Small Business RV Series Routers Stack-b...,2022-03-03,"A vulnerability in Cisco Small Business RV160,...",Apply updates per vendor instructions.,2022-03-17,Unknown,No,https://nvd.nist.gov/vuln/detail/CVE-2022-20708,CWE-121,2022-02-10T17:06:27.109Z,PUBLISHED,10.0,CRITICAL,NETWORK,Multiple vulnerabilities in Cisco Small Busine...
220,CVE-2025-25181,Advantive,VeraCore,Advantive VeraCore SQL Injection Vulnerability,2025-03-10,Advantive VeraCore contains a SQL injection vu...,"Apply mitigations per vendor instructions, fol...",2025-03-31,Unknown,No,https://advantive.my.site.com/support/s/articl...,CWE-89,2025-02-03T00:00:00.000Z,PUBLISHED,5.8,MEDIUM,NaN,A SQL injection vulnerability in timeoutWarnin...
594,CVE-2022-32894,Apple,iOS and macOS,Apple iOS and macOS Out-of-Bounds Write Vulner...,2022-08-18,Apple iOS and macOS contain an out-of-bounds w...,Apply updates per vendor instructions.,2022-09-08,Unknown,No,"https://support.apple.com/en-gb/HT213412, http...","CWE-20, CWE-787",2022-08-24T00:00:00.000Z,PUBLISHED,7.8,HIGH,LOCAL,An out-of-bounds write issue was addressed wit...
429,CVE-2023-36033,Microsoft,Windows,Microsoft Windows Desktop Window Manager (DWM)...,2023-11-14,Microsoft Windows Desktop Window Manager (DWM)...,Apply mitigations per vendor instructions or d...,2023-12-05,Unknown,No,https://msrc.microsoft.com/update-guide/en-US/...,CWE-822,2023-11-14T17:57:37.286Z,PUBLISHED,7.8,HIGH,NaN,Windows DWM Core Library Elevation of Privileg...
72,CVE-2025-48633,Android,Framework,Android Framework Information Disclosure Vulne...,2025-12-02,Android Framework contains an unspecified vuln...,"Apply mitigations per vendor instructions, fol...",2025-12-23,Unknown,No,https://source.android.com/docs/security/bulle...,NaN,2025-12-08T16:57:49.260Z,PUBLISHED,5.5,MEDIUM,LOCAL,In hasAccountsOnAnyUser of DevicePolicyManager...
448,CVE-2023-20109,Cisco,IOS and IOS XE,Cisco IOS and IOS XE Group Encrypted Transport...,2023-10-10,Cisco IOS and IOS XE contain an out-of-bounds ...,Apply mitigations per vendor instructions or d...,2023-10-31,Unknown,No,https://sec.cloudapps.cisco.com/security/cente...,CWE-787,2023-09-27T17:23:21.589Z,PUBLISHED,6.6,MEDIUM,NETWORK,A vulnerability in the Cisco Group Encrypted T...
181,CVE-2025-27363,FreeType,FreeType,FreeType Out-of-Bounds Write Vulnerability,2025-05-06,FreeType contains an out-of-bounds write vulne...,"Apply mitigations per vendor instructions, fol...",2025-05-27,Unknown,No,This vulnerability affects a common open-sourc...,CWE-787,2025-03-11T13:28:31.705Z,PUBLISHED,8.1,HIGH,NaN,An out of bounds write exists in FreeType vers...
131,CVE-2025-20281,Cisco,Identity Services Engine,Cisco Identity Services Engine Injection Vulne...,2025-07-28,Cisco Identity Services Engine contains an inj...,"Apply mitigations per vendor instructions, fol...",2025-08-18,Unknown,No,https://sec.cloudapps.cisco.com/security/cente...,CWE-74,2025-06-25T16:11:42.285Z,PUBLISHED,10.0,CRITICAL,NETWORK,A vulnerability in a specific API of Cisco ISE...
231,CVE-2024-20953,Oracle,Agile Product Lifecycle Management (PLM),Oracle Agile Product Lifecycle Management (PLM...,2025-02-24,Oracle Agile Product Lifecycle Management (PLM...,Apply mitigations per vendor instructions or d...,2025-03-17,Unknown,No,https://www.oracle.com/security-alerts/cpujan2...,CWE-502,2024-02-17T01:50:16.976Z,PUBLISHED,8.8,HIGH,NETWORK,Vulnerability in the Oracle Agile PLM product ...
277,CVE-2024-44309,Apple,Multiple Products,Apple Multiple Products Cross-Site Scripting (...,2024-11-21,"Apple iOS, macOS, and other Apple products con...",Apply mitigations per vendor instructions or d...,2024-12-12,Unknown,No,"https://support.apple.com/en-us/121752, 

## Checking Joins

In [6]:

print(f"Pre-Join CISA Count: {len(df_nvd)}")  
print(f"Pre-Join NVD Count:  {len(df_cve)}")  
print(f"Post-Join SQL Count: {len(joined_df)}")

match_rate = (len(joined_df) / len(df_nvd)) * 100
print(f"Overall Match Rate:  {match_rate:.2f}%")

print("\nJoined Dataset Sample:")
print(joined_df.head())

Pre-Join CISA Count: 1716
Pre-Join NVD Count:  143544
Post-Join SQL Count: 649
Overall Match Rate:  37.82%

Joined Dataset Sample:
           cve_id vendorProject            product  \
0  CVE-2025-39964         Linux             Kernel   
1  CVE-2025-39682         Linux             Kernel   
2  CVE-2025-25249      Fortinet  Multiple Products   
3  CVE-2023-49105      ownCloud           ownCloud   
4   CVE-2022-0995         Linux             Kernel   

                                   vulnerabilityName cisa_date_added  \
0          Linux Kernel Race Condition Vulnerability      2026-09-18   
1  Linux Kernel Improper Check for Unusual or Exc...      2026-09-18   
2  Fortinet Multiple Products Heap-based Buffer O...      2026-09-09   
3     ownCloud Improper Authentication Vulnerability      2026-08-27   
4     Linux Kernel Out-of-Bounds Write Vulnerability      2026-08-26   

                                    cisa_description  \
0  Linux Kernel contains a race condition vulnera...   

The reason some of the rows didn't match are likely due to the CVE list containing CVEs released in 2026, and my data only has 2022 up to 2025.

In [7]:
unmatched_cisa_sql = """
    SELECT 
        c.cveID,
        c.vendorProject,
        c.product,
        c.vulnerabilityName,
        c.dateAdded
    FROM cisa_kev c
    LEFT JOIN nvd_cves n 
        ON UPPER(TRIM(c.cveID)) = UPPER(TRIM(n.cve_id))
    WHERE n.cve_id IS NULL;
"""

df_cve.to_sql('nvd_cves', conn, index=False, if_exists='replace')
df_nvd.to_sql('cisa_kev', conn, index=False, if_exists='replace')

unmatched_df = pd.read_sql_query(unmatched_cisa_sql, conn)

print(f"Total Unmatched CISA Rows: {len(unmatched_df)}")
print("\nFirst 10 Unmatched Vulnerabilities:")
print(unmatched_df.head(10))

Total Unmatched CISA Rows: 1067

First 10 Unmatched Vulnerabilities:
            cveID vendorProject                                   product  \
0  CVE-2026-53266         Linux                                    Kernel   
1  CVE-2026-58704        Google                                     Pixel   
2  CVE-2026-76460         Cisco                  Identity Services Engine   
3  CVE-2026-87886       Acronis                                    Backup   
4  CVE-2026-76461         Cisco                      Secure Email Gateway   
5  CVE-2026-84869   ConnectWise                             ScreenConnect   
6  CVE-2026-42016         JFrog                               Artifactory   
7  CVE-2026-42018         JFrog                               Artifactory   
8  CVE-2026-85706        GitLab  Community Edition and Enterprise Edition   
9  CVE-2026-86060      MikroTik                                  RouterOS   

                                   vulnerabilityName   dateAdded  
0     Linux Kern

## Business problem
Target variable is attack_vector, and the independant variables are the other columns.

The business stakeholders are large companies with sensitive data that are constantly attacked by organizations looking to steal their data for profit or information on their technology. 

In [68]:
known_df= joined_df[joined_df["knownRansomwareCampaignUse"]!="Unknown"]
print(known_df)
# known_df
known_df["attack_vector"].value_counts() 

             cve_id vendorProject                                    product  \
13    CVE-2024-1708   ConnectWise                              ScreenConnect   
16   CVE-2024-57728   SimpleHelp                                  SimpleHelp   
17   CVE-2024-57726   SimpleHelp                                  SimpleHelp   
19   CVE-2023-27351      PaperCut                                      NG/MF   
22   CVE-2024-27199     JetBrains                                   TeamCity   
..              ...           ...                                        ...   
621  CVE-2022-22954        VMware  Workspace ONE Access and Identity Manager   
622  CVE-2022-24521     Microsoft                                    Windows   
633  CVE-2022-21999     Microsoft                                    Windows   
641  CVE-2022-24682       Synacor             Zimbra Collaborate Suite (ZCS)   
647  CVE-2022-21882     Microsoft                                     Win32k   

                                     vu

attack_vector
NETWORK             87
LOCAL                5
ADJACENT_NETWORK     2
Name: count, dtype: int64

## Messiness in data
Some rows are missing values for the attack_vector column like in rows 647 or 220 in the joined table.


In [ ]:
print(joined_df.iloc[647][["cve_id","attack_vector"]])
print(joined_df.iloc[220][["cve_id","attack_vector"]])


cve_id           CVE-2022-21882
attack_vector               NaN
Name: 647, dtype: object
cve_id           CVE-2025-25181
attack_vector               NaN
Name: 220, dtype: object
